### ISSUE TITLE
Page accueil public

### ISSUE THREAD

**Issue by LeMustelide** [LeMustelide/creacosm#4]

**Comment by yoanbaulande** [comment]
Maquette : 
![image](https://user-images.githubusercontent.com/64960794/218585758-e226e05a-15cc-41d7-bbc7-caeaea2970b1.png)

**Comment by yoanbaulande** [comment]
Avancement de la page d'accueil public, encore quelques parties et détails à faire pour la première section.

![image](https://user-images.githubusercontent.com/64960794/219178438-f3f39ea1-d52c-407a-943b-22ac94c02c4d.png)
